background {
    monitor =
    color = rgba(1e1e2eff)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(cba6f7)
    inner_color = rgb(313244)
    font_color = rgb(cdd6f4)
    placeholder_text = <i>Password</i>
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M | %d.%m.%Y")"
    color = rgba(cdd6f4ff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
